### ISSUE TITLE
Warnings with beta and nightly

### ISSUE THREAD

**Issue by ngrewe** [SSheldon/rust-objc#28]
Hi,

I'm making progress on setting up a travis build job, and it promptly discovered a few warnings when building rust-objc with rust beta or nightly:

```
src/runtime.rs:108:38: 108:43 warning: found non-foreign-function-safe member in struct marked #[repr(C)]: found zero-size struct in foreign module, consider adding a member to this struct, #[warn(improper_ctypes)] on by default
src/runtime.rs:108     pub fn class_getName(cls: *const Class) -> *const c_char;
                                                        ^~~~~
```
That's caused by `PrivateMarker` being a unit struct. So it affects `Class`, `Object`, `Ivar`, and `Method`. Not sure what to do here. It's not really a dangerous thing since you only ever manipulate pointers to these structs, but it would still be nice to have this handled properly.

**Comment by SSheldon** [comment]
Turns out that while unit structs are not considered foreign-function-safe, empty enums are. So converting PrivateMarker to an empty enum resolves the warning! (Why not just make things like Class, Object, etc empty enums? I want them to continue to appear as structs in the docs.)

Fixed in dfa8b48.
