### ISSUE TITLE
Should gnustep be a feature?

### ISSUE THREAD

**Issue by SSheldon** [SSheldon/rust-objc#34]
Features for crates are usually used for optional functionality. GNUstep support is currently implemented as a feature, but that might not be the right way to think about it. Using GNUstep on Linux isn't really optional, and there doesn't seem to be a use case for using it on OSX when Apple's Objective-C runtime is available.

Perhaps this would be better handled as a configuration, not a feature. A build script could detect whether Apple's runtime is available or the GNUstep runtime and emit `cargo:rustc-cfg=gnustep` accordingly. It's not clear to me how this detection should be done.

**Comment by ngrewe** [comment]
Yes. I've in fact been wondering about that myself. The reason that I made it a feature originally was to avoid tying GNUstep support to a specific target OS. Apart from Linux, FreeBSD has stellar GNUstep support, and at least in theory the runtime should be able to target Windows as well (not that I have ever tried…), so `#[cfg()]`ing by target didn't seem to be a nice thing to do.

I think there are two things that could potentially work:

* You could go down the route of selecting the runtime based on the target, but treating the Apple runtime as the special case, so that it would be used for *-apple-darwin targets, and the GNUstep runtime everywhere else.
* You could do the autoconf-y thing and try to link a program that references a symbol that is specific to the GNUstep runtime. I think the [`objc_test_capability()` feature test function](https://github.com/gnustep/libobjc2/blob/f50bc6cf338689a63bb6d1fe46a04991b4160419/objc/capabilities.h#L139) might be a good choice.

The first option still seems really indirect in inferring the runtime from the target, and would break if the set of supported platforms ever becomes overlapping, but maybe it's okay for the time being? Obviously there might be the faint possibility somebody building a darwin system from scratch and trying to throw GNUstep and rust at it, but I don't think that should be a big concern.

The second option would make an accurate decision in more cases, but it would pull in a build dependency on the gcc crate, so I'd be leaning towards the first option.

**Comment by SSheldon** [comment]
Yeah, I also think the second option might not work well with cross-compiling. For example, let's say I'm trying to build for iOS, with the build script it'd be easy to check what my system supports, but I don't see how it can check what the target supports.

I agree that option one seems to be the simplest for now.

@ngrewe, another thing I've been thinking about is supporting ObjC 1 and 2. If possible that'd be good for GNUstep, given that package managers seem to have the GNUstep ObjC 1 runtime. I haven't come up with a great way to differentiate them, though; could do some crazy `dlsym` checks at runtime to see if the ObjC2 functions are available, dunno...
