### ISSUE TITLE
code relies on type inference rules which are likely to change

### ISSUE THREAD

**Issue by Hossein-Noroozpour** [SSheldon/rust-objc#55]
probably msg_send macro is using type inference rules which will be removed in the next coming rustc.
my current rustc version is rustc 1.19.0-nightly (d015610db 2017-06-05)

complete warning is:
- note: #[warn(resolve_trait_on_defaulted_unit)] on by default
- warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
- note: for more information, see issue #39216 <https://github.com/rust-lang/rust/issues/39216>
- note: this error originates in a macro outside of the current crate

**Comment by SSheldon** [comment]
@Hossein-Noroozpour, can you share a snippet of your code that's triggering this warning?

Is it possible that you have some code that looks like this, with no annotated return type?
``` rust
msg_send![obj, retain];
```

If so, I believe it should be fixed by adding a type annotation, like:
``` rust
let _: () = msg_send![obj, retain];
```

Let me know if the `msg_send!` usage that causes this error is in the objc crate, but otherwise I think this is something that users of the crate will need to fix themselves.

**Comment by Hossein-Noroozpour** [comment]
Thanks, yes, this `()` was the problem.  I think maybe you like to see this: https://stackoverflow.com/questions/44597919/simd-encoding-for-objective-c-runtime/44610154#44610154
the SIMD types have a weird problem in encoding, and unfortunately they are important part of the today graphic system of Mac OS.

**Comment by SSheldon** [comment]
Great, glad that fixed your problem!

Hmm, yeah, that's really interesting that the runtime just entirely skips simd arguments in encodings... definitely not what I would expect. I'll keep that in mind as I work on `verify_message`! (And now I'm curious to look into simd more, I haven't investigated it much...) Thanks for letting me know!
