### ISSUE TITLE
msg_send! still compiles when the return type cannot be inferred (relying on behavior that will change in future versions of Rust)

### ISSUE THREAD

**Issue by mrmekon** [SSheldon/rust-objc#62]
This is probably not a bug that needs to be fixed in rust-objc, but a warning to developers since it causes runtime crashes with unclear errors.

Previously, both of these worked, assuming setThing: returned void:
```
let _ = msg_send![obj, setThing: 1];
msg_send![obj, setThing: 0];
```

They worked because Rust inferred unknown types as ().  As of recent Rust nightly builds, unknown types are inferred as a new '!' type (see: https://github.com/rust-lang/rust/issues/48950).

Unfortunately, Rust will build it and the crashes occur at runtime.  Depending on which features you have compiled rust-objc with, you either get a panic at the calling line, a panic in objc_exception, or a segfault.

The error messages are entirely unhelpful unless you build rust-objc with the `verify_message` feature, which catches it at compile-time.

Fix by forcing the type back to ():
```
let _: () = msg_send![obj, setThing: 1];
```

**Comment by kvark** [comment]
Any plans for a proper fix? This affects us greatly in metal-rs.

**Comment by alecmocatta** [comment]
@kvark I believe the fix should be either in metal-rs: adding `let () =` before relevant `msg_send`s, or rustc changing what type inference defaults to on unconstrained types. Either way, looks like rustc will revert and avoid stabilising till ramifications are clearer https://github.com/rust-lang/rust/issues/49691

**Comment by SSheldon** [comment]
I didn't even know it would compile if you omit the `let _: () =` when using `msg_send!`! Sorry to hear this caused folks trouble. Unfortunately I'm not aware of anything that we can do in the `objc` crate to avoid this...

If the rustc change gets shipped again, it seems like the only way to fix would be to add the type annotations. I'll close this out because I'm not aware of any action `objc` can take, but if anyone has an idea let me know!

**Comment by SSheldon** [comment]
I haven't fully understood this issue. I thought this was unavoidable, but after @SimonSapin's comment https://github.com/rust-lang/rust/pull/65355#issuecomment-542166585, it turns out that the un-annotated usage only compiles because of a quirk in objc's macro and the type resolution.

For example, the following code will not compile:
``` rust
mem::zeroed();
```

You get an error stating "type annotations needed". I would expect that a bare `msg_send!` like the following behaves the same way and would fail to compile:
``` rust
msg_send![obj, release];
```

But as described above, that code is accepted! It infers a `()` return type from `msg_send!`. Why is this? Well, it turns out that the following code _will_ compile:
``` rust
if false {
    panic!("panic")
} else {
    mem::zeroed()
};
```

For some reason, the compiler sees that one branch is `!` and the other is `_` and decides that the type must be `()`. There is a comparable code structure inside the `msg_send!` macro which results in the same behavior. With the change to stabilize `!`, the compiler will instead infer that the type here is `!`, and undefined behavior ensues.

With that understanding, there is in fact something we can do here: change the structure of the code inside the macro so that bare `msg_send!` is not accepted, and correctly errors requiring an explicit return type. This will prevent users from relying on this quirk in type resolution while unblocking the Rust devs on stabilizing `!`.
