### ISSUE TITLE
Cache `Class::get`

### ISSUE THREAD

**Issue by grovesNL** [SSheldon/rust-objc#65]
Currently gfx spends a [significant amount of time](https://github.com/gfx-rs/gfx/issues/2161) calling [`Class::get`](https://github.com/SSheldon/rust-objc/blob/master/src/runtime.rs#L266).

Similarly to #64, would it be possible to cache these calls somehow? Perhaps there could be a macro that provides this, like `class!("NSObject")`.

We could try to add this to metal-rs directly for the places we need it ([example](https://github.com/gfx-rs/metal-rs/blob/master/src/depthstencil.rs#L45)), but we also need this change in other crates (for example, we frequently create [`NSAutoreleasePool`](https://github.com/servo/core-foundation-rs/blob/master/cocoa/src/foundation.rs#L185)), so it would be great if we could find a way to add this into objc.

cc @kvark @jrmuizel

**Comment by SSheldon** [comment]
I'm working on a macro that caches the lookup, but @grovesNL it's worth noting you can avoid the lookup entirely and link the class. Like this:
``` rust
extern {
    #[link_name = "OBJC_CLASS_$_NSObject"]
    static OBJC_CLASS: Class;
}
let cls = unsafe { &OBJC_CLASS }
```

Unfortunately I can't do that with a declarative macro because there's no way to use inputs to the macro inside the link directive. But it's doable with a procedural macro, and I've got [a different macro working in objc-foundation-derive](https://github.com/SSheldon/rust-objc-foundation/blob/77005634420f90a15215c89eea7635b8150dec3f/derive/src/lib.rs#L31) that does this.

**Comment by grovesNL** [comment]
@SSheldon The new macro looks great. We'll try it out soon, thanks!
