### ISSUE TITLE
Do a new release.

### ISSUE THREAD

**Issue by jrmuizel** [SSheldon/rust-objc#66]
It would be nice to have a new release with selector caching.

**Comment by kvark** [comment]
As for us, using a cargo override (at the portability's root toml) works fine during development. I'd love to see #65 resolved in an eventually published version.

**Comment by SSheldon** [comment]
I was going to publish a while ago but hit something that needed a bit more thought. The objc crate doesn't specify a minimum required version of rust, but it works pretty far back (maybe all the way to 1.0). When testing the new version I realized it stopped working on at least 1.14 because of:
* omitting the field name when initializing `Sel`, which requires rust 1.17
* using `AtomicPtr::new` in a constant, which requires rust 1.24

I don't know if anyone is still using objc on rust pre-1.24 and objc doesn't have any official policy about this, but... I'm a little uncomfortable bumping the minimum version up so far in a patch version.

I might look into how to make this change backwards compatible before publishing.

**Comment by SSheldon** [comment]
Version 0.2.3 is published!
