### ISSUE TITLE
objc 0.3 hasn't been published

### ISSUE THREAD

**Issue by kettle11** [SSheldon/rust-objc#89]
The malloc_buf version for rust-objc on crates.io is set to version "^0.0".

As a result version 0.0.6 of malloc_buf is pulled. 

You can verify by looking at the crate index here: https://github.com/rust-lang/crates.io-index/blob/master/ob/jc/objc#L25

The cargo.toml for rust-objc specifies version "1.0" of malloc_buf and has done so for 3 years.

I'm not sure what's causing this, but it's not right. :)

**Comment by SSheldon** [comment]
The Cargo.toml you see on the master branch of rust-objc is for a yet-unreleased version of the crate with breaking changes. I started developing some of the breaking changes 3 years ago but only merged them to master last year. The breaking change version hasn't been published yet because there's always some more things I want to sort out and there hasn't been a super compelling need for it yet. There are dozens of crates (some pretty fundamental) relying on objc 0.2 and using it as a public dependency, so they'll all need to be updated simultaneously, so publishing 0.3 is going to be really disruptive. I want to make sure it has a good value proposition.

**Comment by kettle11** [comment]
Ah, ok. That all makes sense! 

I was confused as I assumed you were publishing from master given the way the version numbers match up to the version on crates.io
